"""Add new fields and constraints

Revision ID: 8ad7979a57ce
Revises: 4e01bd66eb35
Create Date: 2026-07-28 15:52:06.493192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad7979a57ce'
down_revision: Union[str, Sequence[str], None] = '4e01bd66eb35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), server_default='MEDIUM', nullable=True))
        batch_op.add_column(sa.Column('task_type', sa.Enum('ASSIGNMENT', 'EXAM', 'PROJECT', 'REVIEW', 'READING', 'OTHER', name='tasktype'), server_default='OTHER', nullable=True))
        batch_op.add_column(sa.Column('estimated_minutes', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_subject_id_subjects'), 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('position')
        batch_op.drop_column('estimated_minutes')
        batch_op.drop_column('task_type')
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
