"""add_pomodoro_fields

Revision ID: b6dc0c103d33
Revises: 8ad7979a57ce
Create Date: 2026-07-28 16:19:27.749255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dc0c103d33'
down_revision: Union[str, Sequence[str], None] = '8ad7979a57ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pomodoro_sessions_subject_id_subjects'), 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pomodoro_sessions_subject_id_subjects'), type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('start_time')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
